[package]
name = "releasable"
version = "0.1.1-dev"
authors = ["Fran√ßois Mockers <mockersf@gmail.com>"]
edition = "2018"
description = "just testing flow"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
